### ISSUE TITLE
Collectionないときの処理がバグってそう

### ISSUE THREAD

**Issue by yumechi** [yumechi/connpass-notification-bot#15]
```
Loading .env environment variables…
Traceback (most recent call last):
  File "src/main.py", line 27, in <module>
    Application.run()
  File "src/main.py", line 15, in run
    result, event_key, post_setting["event_name"]
  File "/home/yumechi-1/work/connpass-notification-bot/src/message/MessageTemplate.py", line 32, in create_message
    diff_key="member",
  File "/home/yumechi-1/work/connpass-notification-bot/src/bot/firebase.py", line 30, in content_diff
    if kind_key not in firebase_data:
TypeError: argument of type 'NoneType' is not iterable
```

FirebaseからNULLが帰ってきたときの処理がおそらくおかしい。取得処理で微妙だっったときに初期値をセットするのを入れてあげないとだめ。

**Comment by yumechi** [comment]
このコミットで解消

https://github.com/yumechi/connpass-notification-bot/commit/a95f87d592378d1597c91d4c60615a63b5b0ca39
